title: "Shash Data Automation"
description: "Python automation, Excel cleanup & data analysis portfolio"
author:
  name: "Shash"
  email: "sri.shash93@gmail.com"
theme: jekyll-theme-cayman

# So links work everywhere
url: "https://sri-shash.github.io"
baseurl: "/Portfolio"

collections:
  projects:
    output: true
    permalink: /projects/:name/
